### ISSUE TITLE
US#09

### ISSUE THREAD

**Issue by On-Fi** [On-Fi/DIY-App#9]

**Comment by On-Fi** [comment]
## Value proposition
As a user
I want to have an overview of my projects (projects I created in the app)
In order to get a overview of all of my projects and edit them from there
## Description
![Image](https://github.com/On-Fi/DIY-App/assets/149980693/23a422fd-76ac-4805-a289-d6e692cb2f9e)
## Acceptance criteria
- [ ] On the profile page each user can upload 
   a profile photo and edit the username
- [ ] There are links to the favorites page and to "my projects"
## Tasks
- [ ] add a button that redirects the user to "my projects"
- [ ] find a way to upload images to the profile page 
- [ ] make the username editable
